trigger:
  - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
      - template: jobs/new-build-job.yml
        parameters:
          config: 'Release'

  - stage: Test
    jobs:
      - template: templates/steps/new-test-step.yml

  - stage: Deploy
    jobs:
      - template: new-templates/deploy/production.yml
